apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yhgw6sd7o-nodejs
  janus-idp.io/tekton: yhgw6sd7o-nodejs
  backstage.io/kubernetes-id: yhgw6sd7o-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yhgw6sd7o-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
